spring:
  r2dbc:
    url: r2dbc:mysql://13.214.234.176:3306:3306/harisma
    username: esemeton
    password: dsj4esemetonserversql
  main:
    web-application-type: reactive
  application:
    name: HRPROJECT

logging:
  level:
    com.dimata.service.general.billing : DEBUG

server:
  port: 8099  